Add database
Dimets/java-filmorate pull request #3
Opened 2022-07-13 12:24 UTC by Dimets

2022-07-13 18:25 UTC, eugene-lenkevich requested changes
Привет,  Дмитрий, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

PS если какие то моменты с SQL сложны то пропускай, но лучше, конечно, разобраться, в реальной жизни очень пригодится :)

2022-07-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> popularFilms = filmStorage.getAllFilms();
Тут вытаскиваются все фильмы, сортируются и, в итоге, отбирается некоторое небольшое их количество. Такой подход не самый оптимальный, плюс если записей слишком много то мы просто получим OutOfMemory
Получится ли сделать такое на SQL, на уровне базы данных такое делать на порядки оптимальней?

Примерно так выглядит запрос на выборку 10и самый залайканых фильмов :)

select likes_count, fild_id from
(select count (user_id) as likes_count, film_id from film_likes group by film_id) as fdata
order by likes_count desc limit 10;

2022-07-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> popularFilms = filmStorage.getAllFilms();
Но это если получится запрос доделать, сильно не настаиваю, все таки не по SQL курс :)

2022-07-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(filmId) == null) {
У тебя же уже используются Optional, тут они были бы как раз
filmStorage.getFilmById(filmId).orElseThrow(...)

2022-07-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.info(String.format("Фильм с id=%d удален:", id) + filmStorage.getFilmById(id));
1. тут второй раз идет запрос в БД за той же записью :)
2. логгер уже умеет в плейсхолдеры, не надо самостоятельно форматировать строку
log.info("Фильм с id={} удален: {}", id", film)

2022-07-13 18:25 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (mpaDao.findMpaById(id).isEmpty()) {
А вообще, тут бы лучше подошел метод isExist(id) :)
запрос в БД был бы примерно такой
https://qna.habr.com/q/892761

2022-07-14 03:25 UTC, Dimets commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> popularFilms = filmStorage.getAllFilms();
Примерно в том же направлении и размышлял, но столкнулся с тем что в postman не проходит тест Film get Popular, он запускается до того как появляются какие от лайки и история с сортировкой уже по объектам Film работает по размеру сета с лайками

2022-07-14 05:02 UTC, Dimets commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(filmId) == null) {
да, согласен, поздно начал использовать и старый код не порефакторил) теперь все доделал

2022-07-14 05:10 UTC, Dimets commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.info(String.format("Фильм с id=%d удален:", id) + filmStorage.getFilmById(id));
поправил

2022-07-14 05:19 UTC, Dimets commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (mpaDao.findMpaById(id).isEmpty()) {
я исходил из того что в контроллере должен быть метод получения Mpa по id, а так получается в service нужно 2 метода, поэтому я сделал его Optional чтобы понимать есть в БД что-то или нет

2022-07-14 11:20 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-07-14 11:25 UTC, merged